services:
  db:
    image: mariadb:12.3
    container_name: sakuku_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: sakuku_backend
    restart: always
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "5000:5000"
    environment:
      PORT: ${PORT}
      DATABASE_URL: "mysql://root:${DB_ROOT_PASSWORD}@db:3306/${DB_NAME}"
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: sakuku_frontend
    restart: always
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "5173:5173"
    environment:
      VITE_API_BASE_URL: "http://localhost:5000/api"
    depends_on:
      - backend

volumes:
  mariadb_data:
